# platform :ios, '7.0'

target 'AfterTaste' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AfterTaste
   pod 'BaiduMapKit'

end

